const express = require('express');
const router = express.Router();

// Import all route modules
const authRoutes = require('./auth');
const onboardingRoutes = require('./onboarding');
const profileRoutes = require('./profile');
const postRoutes = require('./posts');
const engagementRoutes = require('./engagement');
const feedRoutes = require('./feed');
const followRoutes = require('./follow');
const reviewRoutes = require('./reviews');
const messageRoutes = require('./messages');
const enquiryRoutes = require('./enquiries');
const collaborationRoutes = require('./collaborations');
const broadcastRoutes = require('./broadcasts');
const searchRoutes = require('./search');
const notificationRoutes = require('./notifications');
const featureRoutes = require('./features');
const analyticsRoutes = require('./analytics');
const badgeRoutes = require('./badges');
const featuredRoutes = require('./featured');
const adminRoutes = require('./admin');
const settingsRoutes = require('./settings');
const boardRoutes = require('./boards');
const verificationRoutes = require('./verification');
const userRoutes = require('./users');
const moderationRoutes = require('./moderation');
const uploadRoutes = require('./upload');
const featureRoutes = require('./features');
const aiRoutes = require('./ai');

// Mount all routes
router.use('/auth', authRoutes);
router.use('/onboarding', onboardingRoutes);
router.use('/profile', profileRoutes);
router.use('/users', userRoutes);
router.use('/reports', moderationRoutes);
router.use('/posts', postRoutes);
router.use('/engagement', engagementRoutes);
router.use('/feed', feedRoutes);
router.use('/follow', followRoutes);
router.use('/reviews', reviewRoutes);
router.use('/messages', messageRoutes);
router.use('/enquiries', enquiryRoutes);
router.use('/collaborations', collaborationRoutes);
router.use('/broadcasts', broadcastRoutes);
router.use('/search', searchRoutes);
router.use('/notifications', notificationRoutes);
router.use('/features', featureRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/badges', badgeRoutes);
router.use('/featured', featuredRoutes);
router.use('/admin', adminRoutes);
router.use('/settings', settingsRoutes);
router.use('/boards', boardRoutes);
router.use('/verify', verificationRoutes);
router.use('/upload', uploadRoutes);
router.use('/features', featureRoutes);
router.use('/ai', aiRoutes);

module.exports = router;
