const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');
const fs = require('fs');
const path = require('path');
const prisma = new PrismaClient();

// Load curated Internet Archive media (generated by scripts/fetch-archive-media.js)
let ARCHIVE_MEDIA = [];
try {
    const mediaPath = path.join(__dirname, 'archive-media.json');
    if (fs.existsSync(mediaPath)) {
        ARCHIVE_MEDIA = JSON.parse(fs.readFileSync(mediaPath, 'utf8'));
    }
} catch {
    ARCHIVE_MEDIA = [];
}

const LOCATIONS = [
    "Azure Coast, Korali", "Savanna Plains, Umoya", "Coral Bay, Luma Isles", "Skyline Point, Neo City",
    "Aurora Fjords, Nordica", "Emerald Dunes, Solana", "Safari Ridge, Kifaru Reserve", "Lagoon Keys, Marala",
    "Crimson Canyons, Roja", "Mist Valley, Eldoria", "Harbor Lights, Marisport", "Sunrise Peaks, Altura",
];

const CATEGORIES = ["Destinations", "Hotels & Resorts", "Adventures & Activities", "City Life", "Beach", "Safari", "Nature", "Culture & History"];

async function main() {
    console.log("🚀 Starting Nuclear Seed...");

    const passwordHash = await bcrypt.hash("Admin1234", 12);
    const userPasswordHash = await bcrypt.hash("Pass1234!", 12);

    // 1. CREATE ADMIN USER
    console.log("Creating Admin...");
    const admin = await prisma.user.create({
        data: {
            email: "admin@travelpod.com",
            password: passwordHash,
            username: "admin",
            displayName: "System Admin",
            accountType: "ADMIN",
            isAdmin: true,
            onboardingComplete: true
        }
    });

    // 2. CREATE OFFICIAL ACCOUNT
    console.log("Creating Official @travelpod...");
    const official = await prisma.user.create({
        data: {
            email: "official@travelpod.com",
            username: "travelpod",
            displayName: "Travelpod Official",
            isVerified: true,
            accountType: "TRAVEL_AGENCY",
            onboardingComplete: true,
            avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=travelpod"
        }
    });

    // 3. CREATE 40 SEEDED USERS
    console.log("Creating 40 Users...");
    const users = [];

    // 15 Travelers
    for (let i = 1; i <= 15; i++) {
        users.push(await prisma.user.create({
            data: {
                email: `traveler${i}@example.com`,
                username: `traveler${i}`,
                displayName: `Explorer ${i}`,
                password: userPasswordHash,
                accountType: "TRAVELER",
                onboardingComplete: true,
                avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=traveler${i}`,
                personalityTags: ["Solo Traveler", "Foodie", "Culture Hub"],
                preferredRegions: ["Africa", "Asia", "Europe"]
            }
        }));
    }

    // 10 Hotels/Resorts (fictional)
    const hotelNames = ["Azure Dunes Resort", "Savanna Skies Lodge", "Coral Harbor Hotel", "Panorama Heights Suites", "Lagoon Breeze Villas", "Safari Crest Lodge", "Sunset Mirage Resort", "Harborlight Inn", "Skyline Bay Hotel", "Palmstone Retreat"];
    for (let i = 0; i < hotelNames.length; i++) {
        users.push(await prisma.user.create({
            data: {
                email: `hotel${i}@example.com`,
                username: hotelNames[i].toLowerCase().replace(/ /g, ""),
                displayName: hotelNames[i],
                password: userPasswordHash,
                accountType: "HOTEL_RESORT",
                onboardingComplete: true,
                isVerified: i < 5,
                avatarUrl: `https://api.dicebear.com/7.x/identicon/svg?seed=${hotelNames[i]}`
            }
        }));
    }

    // 8 Travel Agencies (fictional)
    const agencyNames = ["Nomad Trails Safaris", "Aurora Journeys", "Wild Meridian Travel", "Coastal Compass Tours", "Skybridge Adventures", "Roamwise Expeditions", "Evertrail Voyages", "Summit & Shore Travel"];
    for (let i = 0; i < agencyNames.length; i++) {
        users.push(await prisma.user.create({
            data: {
                email: `agency${i}@example.com`,
                username: agencyNames[i].toLowerCase().replace(/ /g, ""),
                displayName: agencyNames[i],
                password: userPasswordHash,
                accountType: "TRAVEL_AGENCY",
                onboardingComplete: true,
                isVerified: i < 4,
                avatarUrl: `https://api.dicebear.com/7.x/shapes/svg?seed=${agencyNames[i]}`
            }
        }));
    }

    // 4 Airlines (fictional)
    const airlineNames = ["Equator Air", "SafariSky Airlines", "Oceanic Wings", "AuroraJet"];
    for (let i = 0; i < airlineNames.length; i++) {
        users.push(await prisma.user.create({
            data: {
                email: `airline${i}@example.com`,
                username: airlineNames[i].toLowerCase().replace(/ /g, ""),
                displayName: airlineNames[i],
                password: userPasswordHash,
                accountType: "AIRLINE",
                onboardingComplete: true,
                isVerified: true,
                avatarUrl: `https://api.dicebear.com/7.x/initials/svg?seed=${airlineNames[i]}`
            }
        }));
    }

    // 3 Destination organizations (fictional)
    const destinationNames = ["Korali Islands Tourism Board", "Umoya Savanna Conservancy", "Aurora Fjords Travel Council"];
    for (let i = 0; i < destinationNames.length; i++) {
        users.push(await prisma.user.create({
            data: {
                email: `destination${i}@example.com`,
                username: destinationNames[i].toLowerCase().replace(/ /g, ""),
                displayName: destinationNames[i],
                password: userPasswordHash,
                accountType: "DESTINATION",
                onboardingComplete: true,
                isVerified: true,
                avatarUrl: `https://api.dicebear.com/7.x/pixel-art/svg?seed=${destinationNames[i]}`
            }
        }));
    }

    console.log(`User list size: ${users.length}`);

    // Business Verifications for 10 verified accounts
    const verifiedUsers = users.filter(u => u.isVerified);
    for (let i = 0; i < Math.min(verifiedUsers.length, 10); i++) {
        await prisma.businessVerification.create({
            data: {
                userId: verifiedUsers[i].id,
                businessRegistrationNumber: `BR-${Math.floor(Math.random() * 900000) + 100000}`,
                businessRegistrationDocument: "https://res.cloudinary.com/demo/image/upload/sample.jpg",
                associationName: i % 2 === 0 ? "Global Travel Alliance" : null,
                associationMembershipNumber: i % 2 === 0 ? `KTF-${Math.floor(Math.random() * 90000) + 10000}` : null,
                associationListingUrl: i % 2 === 0 ? "https://travel-association.example.com/members" : null,
                registeredWebsite: `https://${verifiedUsers[i].username}.com`,
                contactEmail: `${verifiedUsers[i].username}@example.com`,
                contactPhone: i % 3 === 0 ? "+254700000000" : null,
                physicalAddress: i % 3 === 0 ? "Nairobi, Kenya" : null,
                status: "APPROVED",
                verifiedAt: new Date()
            }
        });
    }

    // 4. CREATE POSTS USING INTERNET ARCHIVE MEDIA
    console.log("Creating posts from Internet Archive media...");
    const posts = [];

    const media = ARCHIVE_MEDIA.length > 0 ? ARCHIVE_MEDIA : [];
    const totalNeeded = 1200;

    for (let i = 0; i < totalNeeded; i++) {
        const creator = users[i % users.length];
        const location = LOCATIONS[i % LOCATIONS.length];
        const category = CATEGORIES[i % CATEGORIES.length];

        const mediaItem = media.length ? media[i % media.length] : null;
        const isVideo = !!mediaItem?.videoUrl;
        const isImage = !!mediaItem?.imageUrl;

        let postType = 'TEXT';
        let videoUrl = null;
        let mediaUrls = [];
        let thumbnailUrl = null;
        let duration = null;

        if (isVideo) {
            postType = 'VIDEO';
            videoUrl = mediaItem.videoUrl;
            thumbnailUrl = mediaItem.thumbnailUrl || mediaItem.imageUrl || null;
            duration = 30;
        } else if (isImage) {
            postType = 'PHOTO';
            mediaUrls = [mediaItem.imageUrl];
            thumbnailUrl = mediaItem.thumbnailUrl || mediaItem.imageUrl;
        }

        const baseTitle = mediaItem?.title || `Travel in ${location}`;
        const title = `${baseTitle} #${i}`;
        const description =
            mediaItem?.description ||
            `Experience ${category.toLowerCase()} vibes in ${location}. Curated for Travelpod.`;

        posts.push(
            await prisma.post.create({
                data: {
                    userId: creator.id,
                    postType,
                    title,
                    description,
                    videoUrl,
                    mediaUrls,
                    thumbnailUrl,
                    location,
                    locationTag: location,
                    category,
                    duration,
                    tags: ["Travel", category, location.split(" ")[0]],
                    viewCount: Math.floor(Math.random() * 10000),
                },
            }),
        );

        if (i % 50 === 0) console.log(`Created ${i} posts...`);
    }

    // 5. CREATE 54 TRIP BOARDS
    console.log("Creating 54 Trip Boards...");
    const boardTitles = [
        "Savanna Safari Escape", "Island Hopping Adventure", "Hidden City Rooftops", "Fjords & Northern Lights",
        "Indian Ocean Beach Trail", "Mountain Sunrise Treks", "Cultural Streets & Markets", "Weekend Staycations"
    ];
    const boards = [];
    for (let i = 0; i < 54; i++) {
        const creator = users[i % users.length];
        const titleBase = boardTitles[i % boardTitles.length];
        const board = await prisma.tripBoard.create({
            data: {
                userId: creator.id,
                title: `${titleBase} ${Math.floor(i / 8) + 1}`,
                description: `A collection of my favorite moments from ${titleBase}.`,
                destination: titleBase.split(" ").slice(-1)[0],
                isPublic: true
            }
        });
        boards.push(board);

        // Add 5-8 random posts to board
        const randomPosts = [...posts].sort(() => 0.5 - Math.random()).slice(0, Math.floor(Math.random() * 4) + 5);
        for (const post of randomPosts) {
            await prisma.tripBoardVideo.create({
                data: {
                    boardId: board.id,
                    postId: post.id
                }
            }).catch(() => { }); // ignore unique constraint errors if any
        }
    }

    // 6. CREATE ENGAGEMENT DATA
    console.log("Creating Engagement (Likes, Comments, Saves, Follows)...");

    // Likes
    let likesCreated = 0;
    for (let i = 0; i < 5000; i++) {
        const user = users[Math.floor(Math.random() * users.length)];
        const post = posts[Math.floor(Math.random() * posts.length)];
        await prisma.like.create({
            data: { userId: user.id, postId: post.id }
        }).then(async () => {
            await prisma.post.update({ where: { id: post.id }, data: { likeCount: { increment: 1 } } });
            await prisma.user.update({ where: { id: post.userId }, data: { totalLikes: { increment: 1 } } });
            likesCreated++;
        }).catch(() => { });
        if (i % 1000 === 0) console.log(`Created ${i} likes...`);
    }

    // Comments
    const commentTexts = [
        "This place is incredible!",
        "Adding this to my bucket list!",
        "The food here is amazing!",
        "Wow, look at that view!",
        "Great tips, thanks for sharing!",
        "I need to go here ASAP!",
        "Amazing cinematic shots!",
        "This destination looks unreal!",
    ];
    for (let i = 0; i < 1000; i++) {
        const user = users[Math.floor(Math.random() * users.length)];
        const post = posts[Math.floor(Math.random() * posts.length)];
        await prisma.comment.create({
            data: {
                userId: user.id,
                postId: post.id,
                content: commentTexts[Math.floor(Math.random() * commentTexts.length)],
                commentType: "COMMENT"
            }
        });
        await prisma.post.update({ where: { id: post.id }, data: { commentCount: { increment: 1 } } });
    }

    // Saves
    for (let i = 0; i < 500; i++) {
        const user = users[Math.floor(Math.random() * users.length)];
        const post = posts[Math.floor(Math.random() * posts.length)];
        await prisma.save.create({
            data: { userId: user.id, postId: post.id }
        }).then(async () => {
            await prisma.post.update({ where: { id: post.id }, data: { saveCount: { increment: 1 } } });
        }).catch(() => { });
    }

    // Follows
    console.log("Creating Follow relationships...");
    for (const user of users) {
        // Follow official account
        await prisma.follow.create({
            data: { followerId: user.id, followingId: official.id }
        }).catch(() => { });

        // Randomly follow 10-20 others
        const followCount = Math.floor(Math.random() * 11) + 10;
        const others = users.filter(u => u.id !== user.id).sort(() => 0.5 - Math.random()).slice(0, followCount);
        for (const other of others) {
            await prisma.follow.create({
                data: { followerId: user.id, followingId: other.id }
            }).catch(() => { });
        }
    }

    // 7. CREATE FEATURE FLAGS
    console.log("Creating Feature Flags...");
    const flags = [
        { name: "sponsored_promotions", isEnabled: false, description: "Boost Post feature for businesses" },
        { name: "gamification", isEnabled: false, description: "Badges and achievements system" },
        { name: "collaborations", isEnabled: false, description: "Brand and creator collaboration requests" }
    ];
    for (const flag of flags) {
        await prisma.featureFlag.create({ data: flag });
    }

    // 8. CREATE APP VERSION
    console.log("Creating App Version...");
    await prisma.appVersion.create({
        data: {
            currentVersion: "1.0.5",
            minimumVersion: "1.0.5",
            forceUpdate: false,
            releaseNotes: "Bug fixes and performance improvements",
            downloadUrl: "https://github.com/waithakateddy045-stack/travelpod/releases/latest"
        }
    });

    // 9. SEED BADGES
    console.log("Seeding Badges...");
    const badgesData = [
        { name: "🌍 Explorer", tier: "BRONZE", icon: "🌍", description: "Uploaded first video", criteria: { type: "posts", count: 1 } },
        { name: "✈️ Frequent Flyer", tier: "SILVER", icon: "✈️", description: "Uploaded 10 videos", criteria: { type: "posts", count: 10 } },
        { name: "🦁 Safari King", tier: "GOLD", icon: "🦁", description: "Posted Africa/Kenya content 5 times", criteria: { type: "posts", count: 5, category: "Safari" } },
        { name: "🏖️ Beach Lover", tier: "SILVER", icon: "🏖️", description: "Posted beach content 5 times", criteria: { type: "posts", count: 5, category: "Beach" } },
        { name: "💫 Rising Star", tier: "BRONZE", icon: "💫", description: "Received 100 likes", criteria: { type: "likes", count: 100 } },
        { name: "⭐ Influencer", tier: "GOLD", icon: "⭐", description: "Received 1000 likes", criteria: { type: "likes", count: 1000 } },
        { name: "🤝 Social Butterfly", tier: "BRONZE", icon: "🤝", description: "Followed 50 people", criteria: { type: "following", count: 50 } },
        { name: "📸 Content Creator", tier: "SILVER", icon: "📸", description: "Uploaded 25 videos", criteria: { type: "posts", count: 25 } },
        { name: "🏆 Verified Partner", tier: "GOLD", icon: "🏆", description: "Got business verification", criteria: { type: "verification", status: "APPROVED" } },
        { name: "👑 Travelpod Elite", tier: "PLATINUM", icon: "👑", description: "Received 10000 likes", criteria: { type: "likes", count: 10000 } }
    ];
    for (const badge of badgesData) {
        await prisma.badge.create({ data: badge });
    }

    // 10. CREATE 5 PINNED POSTS on @travelpod
    console.log("Creating 5 Pinned Posts for @travelpod...");
    const pinnedPosts = [
        { title: "Welcome to Travelpod 🌍", desc: "The future of video-first travel is here. Discover, connect, and explore like never before." },
        { title: "How to Use Trip Boards 🗺️", desc: "Plan your next adventure by saving videos to your personal or public Trip Boards." },
        { title: "Business Verification ✅", desc: "Get established as a trusted travel provider and reach more customers directly." },
        { title: "How to Book Travel 📅", desc: "Inquire about services directly through the app to start your booking journey." },
        { title: "Upload Your Travel Story 🎬", desc: "Share your honest experiences and tips with the community to earn rewards." }
    ];
    for (let i = 0; i < pinnedPosts.length; i++) {
        await prisma.post.create({
            data: {
                userId: official.id,
                postType: "VIDEO",
                title: pinnedPosts[i].title,
                description: pinnedPosts[i].desc,
                videoUrl: media[i % (media.length || 1)]?.videoUrl || null,
                thumbnailUrl: media[i % (media.length || 1)]?.thumbnailUrl || null,
                isPinned: true,
                duration: 30,
                category: "Culture"
            }
        });
    }

    console.log("✅ Seed Successful!");
    console.log("--------------------------------");
    const userCount = await prisma.user.count();
    const postCount = await prisma.post.count();
    const boardCount = await prisma.tripBoard.count();
    const likeCount = await prisma.like.count();
    const followCount = await prisma.follow.count();

    console.log(`Summary:`);
    console.log(`- Users: ${userCount}`);
    console.log(`- Posts: ${postCount}`);
    console.log(`- Boards: ${boardCount}`);
    console.log(`- Likes: ${likeCount}`);
    console.log(`- Follows: ${followCount}`);
    console.log(`- Admin Credentials: admin@travelpod.com / Admin1234`);
    console.log("--------------------------------");

}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
